# Setup

title:            B. J. Noh
tagline:          Online CV
description:      Here is Byeongjoon Noh's Online CV. If you have any questions, feel free to contact me at 
url:              https://benchoi93.github.io
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
